#!/bin/bash

# This script will use Silver to build an AG evaluator for the
# tutorials grammar tutorials:dc:bin.  If Silver is successful it will
# then run ant to compile the generated Java code ("&& ant") that
# implements the AG evaluator.

# invoke as               ./silver-compile
# or add arguments, like  ./silver-compile --clean

java -jar ../../../jars/RunSilver.jar $@ tutorials:dc && ant

# To run dc, run the generated jar with a arithmetic expression provided
# on the command line.  For example, type:
#  java -jar tutorials.dc.jar "1 + 2"

