----------------------------------------------------
-- THIS FILE IS AUTOMATICALLY GENERATED.          --
-- DO NOT EDIT - ANY CHANGES WILL BE OVERWRITTEN. --
----------------------------------------------------

grammar edu:umn:cs:melt:tutorial:expr:composed:expr_extended_let ; 
export edu:umn:cs:melt:tutorial:expr:composed:expr_extended_let ; 


import edu:umn:cs:melt:tutorial:expr:host ; 
export edu:umn:cs:melt:tutorial:expr:host with parse as hostParse; 
syntax edu:umn:cs:melt:tutorial:expr:host ; 

import edu:umn:cs:melt:tutorial:expr:exts:extended_let ; 
export edu:umn:cs:melt:tutorial:expr:exts:extended_let hiding parse ; 
syntax edu:umn:cs:melt:tutorial:expr:exts:extended_let ; 


