#!/usr/bin/env bash

# Build all grammars in a single invocation of Silver, but don't translate.
# This is quicker thatn make-compiler for running analyses/refactorings.
# Run with --clean --mwda to run the modular well definedness analysis.

set -eu

export SILVER_HOME=$(pwd)
JVM_ARGS="-Xss20M -Xmx6G -jar ../jars/silver.compiler.composed.Default.jar --no-stdlib --dont-translate"
export GRAMMAR_PATH="../grammars"

mkdir -p build
cd build

time java $JVM_ARGS $@ silver:compiler:composed:Default
