#!/bin/bash

set -eu

export SILVER_HOME=$(pwd)
JVM_ARGS="-Xss16M -Xmx3G -jar ../jars/silver.compiler.composed.Default.jar"

# just run this script, no parameters or options.
# One new option: --newcore, for when the core FFI stuff has to change in tandem with the runtime
# Only I should ever have to use this, as once it's done ONCE, fetch-jars will eliminate anyone else's need to do it.

mkdir -p build
cd build

if [ -d ../generated/bin/common ]; then
 # oh man, let's make sure stale runtimes aren't causing us serious problems here
 rm -rf ../generated/bin/common
fi

# Modifications may have been made to how the translation is done

echo "One full cycle ..."
echo ""
echo " > Silver Build"
echo "   Silver Build"
echo "   Runtime"
echo "   Silver Build"
echo ""
time java $JVM_ARGS --relative-jar --clean silver:compiler:composed:Default
ant
mv silver.compiler.composed.Default.jar ../jars/

# Modifications may need to be made to how core translates, to accomodate translation/runtime changes
if [ $# -gt 0 ] && [ "$1" == "--newcore" ]; then
  echo -e "\a"
  echo " Updates to core should be made NOW, to accomodate a new runtime... "
  read
fi

# Should backup old jars here

echo "Before we start, let's get this thing built ..."
echo ""
echo "   Silver Build"
echo " > Silver Build"
echo "   Runtime"
echo "   Silver Build"
echo ""
java $JVM_ARGS --clean silver:xml:ast
echo "Start ..."
time java $JVM_ARGS --relative-jar --clean silver:compiler:composed:Default

# Modifications may have been made to the runtime

echo "No ant yet! Let's go build the runtime! ..."
echo ""
echo "   Silver Build"
echo "   Silver Build"
echo " > Runtime"
echo "   Silver Build"
echo ""
cd ../runtime/java
ant
mv SilverRuntime.jar ../../jars/
cd ../../build
echo "Now finish ..."
ant
mv silver.compiler.composed.Default.jar ../jars/

# Finally, we should have a fully working binary on all the new code. Run it again to reach a fixed point:

echo "One more full cycle ..."
echo ""
echo "   Silver Build"
echo "   Silver Build"
echo "   Runtime"
echo " > Silver Build"
echo ""
time java -ea $JVM_ARGS --relative-jar --clean silver:compiler:composed:Default
ant
mv silver.compiler.composed.Default.jar ../jars/

# If the last build failed, should restore backup jars

echo -e "\a"

echo "Cleaning out stale runtime class files..."
rm -rf ../generated/bin/common

echo "deep-rebuild success"
