#!/usr/bin/env bash

set -eu

LOCAL_STORE=/web/research/melt.cs.umn.edu/downloads/silver-dev/jars
REMOTE_STORE="http://melt.cs.umn.edu/downloads/silver-dev/jars"

if [[ $* == *--copper* ]]; then
    # Only fetch the Copper jars, if requested
    FILES="CopperCompiler.jar"
else
    FILES="CopperCompiler.jar commonmark-0.17.1.jar silver.compiler.composed.Default.jar SilverRuntime.jar IDEPluginRuntime.jar"
fi

mkdir -p jars

if [ -d $LOCAL_STORE ]; then
  for file in $FILES; do
      cp $LOCAL_STORE/$file jars/
  done
else
  # There's probably a better way to do this!
  # Using -r causes lots of pointless downloads of variations of the index.html
  # even if -A.jar is used they still get downloaded...
  
  URLS=""
  for file in $FILES; do
    URLS="$URLS $REMOTE_STORE/$file"
  done
  
  # We're going to download them to here
  mkdir -p JARS-BAK
  
  # -N Pay attention to timestamps, to avoid needless redownloads.
  # -P jars/  Put the files in jars/
  # -nv Don't be so verbose!
  wget -N -P JARS-BAK/ -nv $URLS
  
  # Always overwrite all the files in jars.
  for file in $FILES; do
      cp JARS-BAK/$file jars/
  done
fi

