#!/bin/bash

#Compile with the doc and clean tags
./self-compile --doc --clean
#Copy the generated documentation into the 
cp -rf generated/doc/silver/* documentation/gen/silver
cp -rf generated/doc/core documentation/gen
cp -rf generated/doc/lib/* documentation/gen/lib

