#!/bin/bash

#Compile with the doc and clean tags
./self-compile --doc --clean
#Copy the generated documentation into the 
cp -rf generated/doc/silver documentation/ref/generated
cp -rf generated/doc/core documentation/ref/generated

