#!/bin/bash

ln -s . silver && tar zcvf silver-dist.tar.gz "--exclude=.svn" "--exclude=*.sv~" silver/generated/whatisthis.txt silver/jars/*.jar silver/bin/ silver/grammars/core/ silver/grammars/tutorials/dc/ silver/grammars/tutorials/turing/ silver/grammars/tutorials/simple/ && rm silver
