#!/usr/bin/env bash

set -eu

export SILVER_HOME=$(pwd)
JVM_ARGS="-Xss20M -Xmx1G -jar ../jars/silver.compiler.composed.Default.jar --no-stdlib --one-jar"
export GRAMMAR_PATH="../grammars"
export ANT_OPTS=-Xss10M

mkdir -p build
cd build

echo    === BUILD CORE JAVA SOURCES ===
time java $JVM_ARGS --include-jar ../runtime/java/SilverRuntime.jar $@ silver:core silver:xml:ast

set +u
# In deep-rebuild, there might be translation changes with corresponding runtime changes,
# so we want to hold off on recompling the runtime until the second pass.
if [ -z "$NORUNTIME" ]; then
    echo    === BUILD JAVA RUNTIME ===
    cd ../runtime/java
    ant
    cd ../../build
fi

echo    === BUILD CORE ===
ant

if [ -z "$NOINSTALL" ]; then
    echo    === INSTALL NEW CORE/RUNTIME ===
    mv silver.core.jar ../jars
fi
