#!/bin/bash

if [ -z "$1" ]; then
  echo "invoke make-dist with a version argument."
  echo "For example:  ./make-dist 0.3.1-rc1"
  exit 1
fi

SV=silver-$1

if [[ -a $SV || -a $SV.tar.gz ]]; then
  echo "error: $SV already exists?"
  exit 1
fi


ln -s . $SV

tar zcvf $SV.tar.gz \
 "--exclude=.svn" "--exclude=*~" "--exclude=*test" \
 $SV/generated/whatisthis.txt $SV/jars/*.jar \
 $SV/support/ \
 $SV/grammars/core/ \
 $SV/tutorials/ \
 $SV/grammars/lib/stringmap/ \
 $SV/grammars/lib/xml/ \
 $SV/grammars/silver/testing/ \
 $SV/COPYING.LESSER \
 $SV/HISTORY \
 $SV/README \
 
 


rm $SV
