#!/usr/bin/env bash

# This does a single-pass build of the Silver compiler and runtime.
# This is normally sufficient if there are no changes to the translation.

set -e

export SILVER_HOME=$(pwd)
JVM_ARGS="-Xss20M -Xmx6G -jar ../jars/silver.compiler.composed.Default.jar --no-stdlib --include-jar ../jars/CopperCompiler.jar --include-jar commonmark-0.17.1.jar --relative-jar"
export GRAMMAR_PATH="../grammars:silver.core.jar:silver.util.jar:silver.langutil.jar:silver.rewrite.jar:silver.regex.jar"
export ANT_OPTS=-Xss10M

NOINSTALL=1 ./make-stdlib $@

cd build

echo    === BUILD COMPILER ===
time java $JVM_ARGS $@ silver:compiler:composed:Default
ant

if [ -z "$NOINSTALL" ]; then
    echo    === INSTALL NEW JARS ===
    mv *.jar ../jars
fi
