#!/bin/bash

set -eu

# Check that the eclipse-plugin directory exists
if [ ! -d eclipse-plugin ]; then
	echo "Make sure you're in the silver directory!" >&2;
	exit -1;
fi

cd eclipse-plugin
exec ./build
