#!/usr/bin/env bash

set -e

export SILVER_HOME=$(pwd)
JVM_ARGS="-Xss20M -Xmx1G -jar ../jars/silver.compiler.composed.Default.jar --no-stdlib --one-jar"
export GRAMMAR_PATH="../grammars"
export ANT_OPTS=-Xss10M

mkdir -p build
cd build

echo    === BUILD CORE JAVA SOURCES ===
time java $JVM_ARGS --include-jar ../runtime/java/SilverRuntime.jar $@ silver:core silver:xml:ast

echo    === BUILD JAVA RUNTIME ===
cd ../runtime/java
ant
cd ../../build

echo    === BUILD CORE ===
ant

if [ -z "$NOINSTALL" ]; then
    echo    === INSTALL NEW CORE/RUNTIME ===
    mv silver.core.jar ../jars
fi
