#!/bin/bash

# Exit on error or undefined variable. Good bash hygiene.
set -eu

# Defaults overridable by setting an environment variable:
SVJVM_FLAGS=${SVJVM_FLAGS:-"-Xmx2000M -Xss8M"}
  # These can be fun sometimes:
  # -XX:+PrintCompilation -verbose:gc -XX:+PrintGCTimeStamps -XX:+PrintGCDetails -XX:-PrintGC
SV_BUILD_TARGET=${SV_BUILD_TARGET:-"silver:composed:Default"}

mkdir -p build
cd build

time java ${SVJVM_FLAGS} -jar ../JARS-BAK/silver.composed.Default.jar --relative-jar -G ../generated $@ ${SV_BUILD_TARGET}
ant

