#!/usr/bin/env bash

set -eu

# Make sure this one annoying random dependency is built
if [[ ! -d generated/src/silver/xml/ast ]]; then
  SV_BUILD_TARGET="silver:xml:ast" ./self-compile
fi

echo    === BUILD JAVA RUNTIME ===
cd runtime/java
ant
echo    === INSTALL NEW RUNTIME ===
cd ../..
cp runtime/java/*.jar jars
