#!/bin/bash

set -e

mkdir -p build
cd build

# These can be fun sometimes:
# -XX:+PrintCompilation
# -verbose:gc -XX:+PrintGCTimeStamps -XX:+PrintGCDetails -XX:-PrintGC
if [ -z "$SVJVM_FLAGS" ]; then
  SVJVM_FLAGS="-Xmx1800M -Xss6M"
fi

# must always be a clean build -- ide modification is slightly broken still
time java $SVJVM_FLAGS -jar ../jars/RunSilver.jar --clean $@ silver:composed:idetest && ant

echo -e "\a"

