#!/usr/bin/env bash

# Exit on error or undefined variable. Good bash hygiene.
set -eu

# Defaults overridable by setting an environment variable:
SVJVM_FLAGS=${SVJVM_FLAGS:-"-Xmx4G -Xss16M"}
  # These can be fun sometimes:
  # -XX:+PrintCompilation -verbose:gc -XX:+PrintGCTimeStamps -XX:+PrintGCDetails -XX:-PrintGC
SV_BUILD_TARGET=${SV_BUILD_TARGET:-"silver:compiler:composed:Default"}

export ANT_OPTS=-Xss10M

mkdir -p build
cd build

time java ${SVJVM_FLAGS} -cp ../jars/CopperCompiler.jar -jar ../jars/silver.compiler.composed.Default.jar $@ ${SV_BUILD_TARGET}
ant

