#!/bin/bash

set -euxo pipefail

# Ensure that a Silver JAR exists.
if [[ -f build/silver.compiler.composed.Default.jar ]]; then
	silver_jar=build/silver.compiler.composed.Default.jar
elif [[ -f jars/silver.compiler.composed.Default.jar ]]; then
	silver_jar=jars/silver.compiler.composed.Default.jar
else
	echo "No Silver JAR; try running ./fetch-jars && ./self-compile" >&2
	exit 1
fi

# Ensure that a Copper JAR exists.
if [[ -f jars/CopperCompiler.jar ]]; then
	copper_jar=jars/CopperCompiler.jar
else
	echo "No Copper JAR; try running ./fetch-jars" >&2
	exit 1
fi

# Ensure that a Silver runtime JAR exists.
if [[ -f runtime/java/SilverRuntime.jar ]]; then
	silver_runtime_jar=runtime/java/SilverRuntime.jar
elif [[ -f jars/SilverRuntime.jar ]]; then
	silver_runtime_jar=jars/SilverRuntime.jar
else
	echo "No Silver runtime JAR; try running ./fetch-jars && ./rebuild-runtime" >&2
	exit 1
fi

# Ensure the META-INF directory exists and is empty.
test ! -d build/META-INF || rm -r build/META-INF
mkdir -p build/META-INF

# Build Silver, directing the native-image agent to output reflection
# information to META-INF.
# TODO: We might be able to just hardcode this? We just need the serialization
# stuff, because Copper uses ObjectInputStream.
SVJVM_FLAGS="${SVJVM_FLAGS:-"-Xmx4G -Xss16M"} -agentlib:native-image-agent=config-output-dir=build/META-INF/native-image"
time java $SVJVM_FLAGS \
	-cp $copper_jar \
	-cp $silver_runtime_jar \
	-jar $silver_jar \
	-o build/silver.compiler.composed.Default.jar \
	silver:compiler:composed:Default

# Ensure the reflection config files were generated.
test -d build/META-INF/native-image

# Build the actual JAR and pack the reflection config files in.
export ANT_OPTS=-Xss10M
cd build
ant
zip silver.compiler.composed.Default.jar -r META-INF
cd ..

# Default to using the Epsilon GC... Hope you've got spare RAM!
epsilon_gc_flag=-H:InitialCollectionPolicy="com.oracle.svm.core.genscavenge.CollectionPolicy\$NeverCollect"
NATIVE_IMAGE_FLAGS="${NATIVE_IMAGE_FLAGS:-$epsilon_gc_flag --no-fallback}"

# Build to a native binary with native-image.
time native-image \
	-cp $copper_jar \
	-cp $silver_runtime_jar \
	-jar build/silver.compiler.composed.Default.jar \
	-H:Name=build/silver-native \
	$NATIVE_IMAGE_FLAGS

# Move the binary to the jars directory.
if [[ -z "${SELF_COMPILE_NATIVE_NOINSTALL:-}" ]]; then
	install build/silver-native jars
fi
