#!/usr/bin/env bash

set -eu

cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# if [[ -n "$(git status --porcelain)" ]]; then
# 	echo "You have uncommitted changes! Refusing to run."
# 	exit 1
# fi

branch_name="$(git rev-parse --abbrev-ref HEAD)"
encoded_branch_name="$(curl -Gso /dev/null -w %{url_effective} --data-urlencode $branch_name "" | cut -c 3-)"
commit_hash="$(git rev-parse HEAD)"

# If your username on the your development machine doesn't match your username
# on foundry, put a block in ~/.ssh/config like the following:
#
# Host foundry.remexre.xyz
#   User nathan
rsync -Pa jars/ foundry.remexre.xyz:/export/scratch/melt-jenkins/${commit_hash}-jars/ --exclude=silver-langserver-launcher.jar

echo "Now go to https://foundry.remexre.xyz/jenkins/job/melt-umn/job/silver/job/$encoded_branch_name/build and"
echo "pass /export/scratch/melt-jenkins/${commit_hash}-jars as OVERRIDE_JARS"
