#!/bin/bash

WHERE_IS_SILVER=../../jars
WHERE_IS_THE_SOURCE=..  # cheating a bit. Current directory should be 'lambda'
WHAT_GRAMMAR_TO_BUILD=lambda

java -jar $WHERE_IS_SILVER/RunSilver.jar \
  -I $WHERE_IS_THE_SOURCE $@ $WHAT_GRAMMAR_TO_BUILD && ant

# The $@ helpfully passes along any arguments this script got to silver.

