#!/bin/bash

java -jar lib.testing.jar \
 tests/core \
 /project/melt3/People/evw/Melt_SVN_http/silver/trunk/tutorials

# /project/melt3/People/evw/Melt_SVN_http/grammars/sandbox/testharness/tests/core \
# /project/melt3/People/evw/Melt_SVN_http/silver/trunk/tutorials/dc \
# /project/melt3/People/evw/Melt_SVN_http/silver/trunk/tutorials/simple 




#/edu/umn/cs/melt/miniHaskell/host
#   /project/melt3/People/evw/Melt_SVN_http/grammars/sandbox/testharness
