#!/bin/bash

# This script will use Silver to build an AG evaluator for the
# tutorials grammar and run ant to compile the resulting Java code.

rm -f tutorials.wriju.host.jar
time java -jar ../../../../jars/RunSilver.jar tutorials:wriju:host && ant

# run ant, see above line, only if silver does not fail (thus &&)
# then run "ant"
# ant

# then run "java -jar tutorials.simple.host.bin.jar <<filename>>"
