#!/bin/bash

set -eu

if [ -d ../../grammars ]; then cd ../..; fi

if [ ! -d grammars ]; then
  echo "Couldn't find Silver root. Run as ./support/scripts/generate-documentation"
  exit 2
fi

#Compile documentation
export GRAMMAR_PATH="grammars"

./support/bin/silver --doc --clean silver:extension:doc:extra

rm ./build.xml
rm ./silver.extension.doc.extra.jar

#Copy the generated documentation into the 
cp -rf generated/doc/silver/* documentation/gen/silver
cp -rf generated/doc/core documentation/gen
cp -rf generated/doc/lib/* documentation/gen/lib

