#!/bin/bash

set -eu

if [ -d ../../grammars ]; then cd ../..; fi

if [ ! -d grammars ]; then
  echo "Couldn't find Silver root. Run as ./support/scripts/profile-silver-compiler"
  exit 1
fi

mkdir -p build
cd build

java -Xss8M -Xmx3000M -Xrunhprof:heap=sites,cpu=samples -jar ../jars/RunSilver.jar --clean silver:composed:Default
