#!/bin/bash

set -eu

if [ -d ../../grammars ]; then cd ../..; fi

if [ ! -d grammars ]; then
  echo "Couldn't find Silver root. Run as ./support/scripts/publish-ide"
  exit 1
fi

IDEDIR="/web/research/melt.cs.umn.edu/downloads/silver-eclipse-beta"
ZIPFILE="generated/ide/silver.composed.idetest/updatesite/target/SILVER_UPDATESITE.zip"

if [ ! -d $IDEDIR ]; then
  echo "Must be running on a umn machine in the melt group."
  exit 1
fi

if [ ! -a $ZIPFILE ]; then
  echo "Should be run from root of silver tree with IDE generated."
  exit 2
fi

echo "..."
echo "Be sure to increment IDE version number in silver:composed:idetest:Main.sv"
echo "..."

rm -Rf ${IDEDIR}/*
cp $ZIPFILE ${IDEDIR}/

cd ${IDEDIR}
unzip SILVER_UPDATESITE.zip
chmod -R go=u *

