#!/bin/bash

set -eu

if [ -x support/nailgun/sv-nailgun ]; then cd support/nailgun; fi

if [ ! -x sv-nailgun ]; then
  echo "Couldn't find Silver root. Run as ./support/nailgun/install-sv-nailgun"
  exit 1
fi

if [ ! -d ~/bin ]; then
  echo "Silver's installer uses ~/bin, but this directory was not found."
  exit 1
fi

echo "Found ~/bin"

case `uname` in
*Darwin*)
  READLINK=greadlink
  if [ ! -f `which greadlink` ]; then
    echo "Missing greadlink. Please install coreutils:"
    echo -e "\tbrew install coreutils"
    exit 4
  fi
  ;;
*)
  READLINK=readlink
  ;;
esac

for file in sv-nailgun sv-call; do
  filename=$(basename "$file")
  if [ -f ~/bin/$filename ]; then
    rm ~/bin/$filename
  fi
  if ln -s "$("$READLINK" -f "$file")" ~/bin/ ; then
    echo "Installed ~/bin/$filename"
  else
    echo "Failed to install ~/bin/$filename"
    exit 1
  fi
done
  
echo "Nailgun scripts installed successfully."

