#!/bin/bash

# This silver-compile script is just like all the others.
# There is not specific here to deal with testing
# (other than ensuring that the testing extension has been
#  compiled into Silver).

export SILVER_HOME=../../../../../../../../../Melt_SVN_http/silver/trunk/jars/


time java -jar $SILVER_HOME/RunSilver.jar $1  -o tests.core.jar \
     edu:umn:cs:melt:testing:tests:core \
     && ant

