#!/bin/bash
set -eu

# build silver.composed.Default.jar
(cd ../
  ./self-compile
  mv build/silver.composed.Default.jar jars/
)

# build SilverRuntime.jar
(cd ../runtime/java/
  ant
  mv SilverRuntime.jar RunSilver.jar ../../jars/
)

# build IDEPluginRuntime.jar
(cd ../runtime/imp/
  ./build.sh
)

# build silver.composed.idetest.jar
(cd ../
  SV_BUILD_TARGET="silver:composed:idetest" ./self-compile --clean
  mv build/silver.composed.idetest.jar jars/
)

cp ../jars/{CopperRuntime,IDEPluginRuntime,SilverRuntime,silver.composed.Default,silver.composed.idetest}.jar plugin/

mvn package

