----------------------------------------------------
-- THIS FILE IS AUTOMATICALLY GENERATED.          --
-- DO NOT EDIT - ANY CHANGES WILL BE OVERWRITTEN. --
----------------------------------------------------

grammar edu:umn:cs:melt:tutorial:expr:composed:expr_ctrans ; 
export edu:umn:cs:melt:tutorial:expr:composed:expr_ctrans ; 


import edu:umn:cs:melt:tutorial:expr:host ; 
export edu:umn:cs:melt:tutorial:expr:host with parse as hostParse; 
syntax edu:umn:cs:melt:tutorial:expr:host ; 

import edu:umn:cs:melt:tutorial:expr:exts:ctrans ; 
export edu:umn:cs:melt:tutorial:expr:exts:ctrans hiding parse ; 
syntax edu:umn:cs:melt:tutorial:expr:exts:ctrans ; 


