#!/bin/bash

# This silver-compile script is just like all the others.
# There is not specific here to deal with testing
# (other than ensuring that the testing extension has been
#  compiled into Silver).

export SILVER_HOME=../..

java -Xmx2000M -Xss8m -jar $SILVER_HOME/jars/RunSilver.jar $@  -o test.jar \
     -I .. stdlib \
     && ant

