#!/bin/bash

# example cron config:
# */10 * * * * /export/scratch/melt-jenkins/custom-silver/support/jenkins/cron-job-publish-jars > /dev/null 2>&1

set -eu

WEB_STORE=/web/research/melt.cs.umn.edu/downloads/silver-dev
JENKINS_DUMP=/export/scratch/melt-jenkins/custom-stable-dump

# On occasion, NFS goes down, just exit gracefully if so

if [ ! -d $WEB_STORE ]; then
  exit 1
fi

if [ ! -d $JENKINS_DUMP ]; then
  exit 2
fi

# We only want to copy the files if they are newer than what's already there.
# Newer, specifically, so that if we manually publish-jars, we don't then overwrite.

# -u Only copy if the source file is newer than the destination file
cp -u $JENKINS_DUMP/*.jar $WEB_STORE/jars
cp -u $JENKINS_DUMP/silver-latest.tar.gz $WEB_STORE

# fix permissions
chgrp -R melt $WEB_STORE/jars $WEB_STORE/silver*
chmod -R 775 $WEB_STORE/jars $WEB_STORE/silver*

# indicate the last successful time in which this script ran
touch /export/scratch/gitbot-deletable-timestamp

