#!/usr/bin/env bash

# example cron config:
# */10 * * * * /export/scratch/melt-jenkins/custom-silver/support/jenkins/cron-job-publish-jars
#
# This script is also used to copy the jars from the silver-ableC extension.

# redirect this script's output to log file, not stdout
exec > /export/scratch/gitbot-deletable-log 2>&1

set -eu

WEB_STORE=/web/research/melt.cs.umn.edu/downloads/silver-dev
JENKINS_DUMP=/export/scratch/melt-jenkins/custom-stable-dump

# On occasion, NFS goes down, just exit gracefully if so

if [ ! -d $WEB_STORE ] || [ ! -d $JENKINS_DUMP ]; then
  echo "NFS down?"
  exit 1
fi

# We only want to copy the files if they are newer than what's already there.
# Newer, specifically, so that if we manually publish-jars, we don't then overwrite.

# -u Only copy if the source file is newer than the destination file
# --remove-destination  deletes so that we take ownership of the file (thus can chgrp/mod)

newgrp cs-melt << EOF
  umask 002
  cp -u --remove-destination $JENKINS_DUMP/*.jar $WEB_STORE/jars
  cp -u --remove-destination $JENKINS_DUMP/silver-latest.tar.gz $WEB_STORE
EOF

echo "Success"
date

