#!/bin/bash

count=0

silver --clean rhs | grep "B_t" > /dev/null || ((count++))
silver --clean disamb | grep "B_t" > /dev/null || ((count++))
silver --clean startMissing | grep "nonterm_b:B" > /dev/null || ((count++))
silver --clean prodMod | grep "B_t" > /dev/null || ((count++))
silver --clean mda | grep "nonterm_b:B" > /dev/null || ((count++))
silver --clean missingLHS | grep "nonterm_b:B" > /dev/null || ((count++))
# terminalLHS doesn't contain a reference to B_t or B
silver --clean terminalLHS | grep "terminalLHS:terminalLHS" > /dev/null || ((count++))

rm -f build.xml

test $count == 0