#!/usr/bin/env bash

export SILVER_HOME=../..

silver() { "$SILVER_HOME/support/bin/silver" "$@"; }

# Always clean build
ARGS="$@ --clean --dont-translate"

count=0
fail=0
pass=0

# Check to ensure all these builds yield the shown string (as an error)
function cst_test {
    silver $ARGS $1 |& grep "$2" > /dev/null
    if [[ $? != 0 ]]
    then
        echo -e "\nFailure: $1 did not produce output $2"
        ((fail++))
    else
        echo -n "."
        ((pass++))
    fi
    ((count++))
}

cst_test rhs "B_t"
cst_test disamb "B_t"
cst_test startMissing "nonterm_b:B"
cst_test prodMod "B_t"
cst_test mda "nonterm_b:B"
cst_test missingLHS "nonterm_b:B"
cst_test terminalLHS "terminalLHS:A_t"
cst_test terminalSubmit "B_t"
cst_test terminalDominate "B_t"
cst_test terminalSubmitLexer "lexer_b:B"
cst_test lexerSubmit "B_t"
cst_test lexerDominate "B_t"
cst_test missingSeparator "test:nonterm_b:Mangle_t"
cst_test multipleSeparators "multipleSeparators:A_t, multipleSeparators:B_t"

echo ""
echo "$pass out of $count tests passed"

rm -f build.xml

exit $fail
